apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cve-webhook-config
webhooks:
- name: cve.find.com
  clientConfig:
    service:
      name: webhook-service
      namespace: default
      path: /validate
      port: 443
    caBundle: <BASE64-CRT>
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
